# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Demand', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField()),
                ('costo', models.IntegerField(default=0)),
                ('ruta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabrica', models.CharField(max_length=200)),
                ('produccion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tienda', models.CharField(max_length=200)),
                ('demand', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo1.Fabrica'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tiend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo1.Tienda'),
        ),
    ]
