# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='Demand',
        ),
        migrations.AlterField(
            model_name='demanda',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
