# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0002_auto_20170213_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=200)),
                ('prot', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fibre', models.FloatField(default=0)),
                ('salt', models.FloatField(default=0)),
            ],
        ),
    ]
