# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversore',
            name='Tipo',
            field=models.CharField(choices=[('MI', 'Micorinversor'), ('IC', 'Inversor Central')], default='IC', max_length=2),
        ),
    ]
