from django.contrib import admin
from .models import Gen, Erc, Central, CentralOv, Centrales, Ofererc, Paqgen, Paquetes, Paquetes2, Nodoof, Regionof, Sistemainter, Zonaof, Paqin, Paqexc, Conpaqexc, Ofertas
admin.site.register(Central)
admin.site.register(CentralOv)
admin.site.register(Centrales)
admin.site.register(Ofererc)
admin.site.register(Paqgen)
admin.site.register(Paquetes)
admin.site.register(Paquetes2)
admin.site.register(Nodoof)
admin.site.register(Regionof)
admin.site.register(Sistemainter)
admin.site.register(Zonaof)
admin.site.register(Paqin)
admin.site.register(Paqexc)
admin.site.register(Conpaqexc)
admin.site.register(Ofertas)
admin.site.register(Gen)
admin.site.register(Erc)