# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrales',
            name='cent_acept',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
