# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0003_auto_20170224_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='central',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrales',
            name='central',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrales',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centralov',
            name='central',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centralov',
            name='paquetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofererc',
            name='erc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofererc',
            name='ofertas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqexc',
            name='conpaqexc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqexc',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqexc',
            name='paquetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqgen',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqgen',
            name='paquetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqin',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqin',
            name='paquetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paqin',
            name='paquetes2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
