# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0004_auto_20170224_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralov',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
