# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0005_auto_20170226_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrales',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofererc',
            name='demc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofererc',
            name='deme',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofererc',
            name='demp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paqgen',
            name='up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
