# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0006_auto_20170226_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrales_sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cen', models.TextField(blank=True, null=True)),
                ('central', models.IntegerField(blank=True, null=True)),
                ('capapl', models.IntegerField(blank=True, null=True)),
                ('zpcen', models.IntegerField(blank=True, null=True)),
                ('zgcen', models.IntegerField(blank=True, null=True)),
                ('zprcen', models.IntegerField(blank=True, null=True)),
                ('zicen', models.IntegerField(blank=True, null=True)),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('prelacion', models.IntegerField(blank=True, null=True)),
                ('zpcen2', models.TextField(blank=True, null=True)),
                ('zgcen2', models.TextField(blank=True, null=True)),
                ('zprcen2', models.TextField(blank=True, null=True)),
                ('zicen2', models.TextField(blank=True, null=True)),
                ('cent_acept', models.TextField(blank=True, max_length=1, null=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentralOv_sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('paquetes', models.IntegerField(blank=True, null=True)),
                ('central', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paqexc_sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('conpaqexc', models.IntegerField(blank=True, null=True)),
                ('paquetes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paqgen_sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquetes', models.IntegerField(blank=True, null=True)),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('capapl', models.IntegerField(blank=True, null=True)),
                ('gpot', models.IntegerField(blank=True, null=True)),
                ('geea', models.IntegerField(blank=True, null=True)),
                ('gcel', models.IntegerField(blank=True, null=True)),
                ('ppaq', models.FloatField(blank=True, null=True)),
                ('firrant', models.IntegerField(blank=True, null=True)),
                ('firrdes', models.IntegerField(blank=True, null=True)),
                ('sint', models.IntegerField(blank=True, null=True)),
                ('zonin', models.IntegerField(blank=True, null=True)),
                ('rin', models.IntegerField(blank=True, null=True)),
                ('nin', models.IntegerField(blank=True, null=True)),
                ('prelacion', models.IntegerField(blank=True, null=True)),
                ('factordevesp', models.FloatField(blank=True, null=True)),
                ('pct20', models.FloatField(blank=True, null=True)),
                ('vpnindexdls', models.FloatField(blank=True, null=True)),
                ('vpnindexpesos', models.FloatField(blank=True, null=True)),
                ('indexusd', models.IntegerField(blank=True, null=True)),
                ('idejec', models.IntegerField(blank=True, null=True)),
                ('nppaq', models.FloatField(blank=True, null=True)),
                ('ev_ppajus', models.IntegerField(blank=True, null=True)),
                ('ev_pporig', models.IntegerField(blank=True, null=True)),
                ('aceptado', models.IntegerField(blank=True, null=True)),
                ('nin2', models.BigIntegerField(blank=True, null=True)),
                ('rin2', models.BigIntegerField(blank=True, null=True)),
                ('zonin2', models.BigIntegerField(blank=True, null=True)),
                ('sint2', models.BigIntegerField(blank=True, null=True)),
                ('zongenf', models.IntegerField(blank=True, null=True)),
                ('fechaap', models.TextField(blank=True, null=True)),
                ('fechaen', models.TextField(blank=True, null=True)),
                ('up', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paqin_sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('paquetes', models.IntegerField(blank=True, null=True)),
                ('paquetes2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
