# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP15', '0007_centrales_sim_centralov_sim_paqexc_sim_paqgen_sim_paqin_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrales_sim',
            name='fac_pot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrales_sim',
            name='limp_cen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrales_sim',
            name='tipo_cent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
