# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa1x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Ene', models.FloatField(default=0)),
                ('Feb', models.FloatField(default=0)),
                ('Mar', models.FloatField(default=0)),
                ('Abr', models.FloatField(default=0)),
                ('May', models.FloatField(default=0)),
                ('Jun', models.FloatField(default=0)),
                ('Jul', models.FloatField(default=0)),
                ('Ago', models.FloatField(default=0)),
                ('Sep', models.FloatField(default=0)),
                ('Oct', models.FloatField(default=0)),
                ('Nov', models.FloatField(default=0)),
                ('Dic', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tarifa1x',
            name='Temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.Temporada'),
        ),
    ]
