# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_auto_20170309_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa1x',
            name='DAC',
            field=models.IntegerField(default=0),
        ),
    ]
