# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0005_auto_20170309_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meses', models.CharField(max_length=50)),
                ('Dias', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='Tarifa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='Verano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Meses'),
        ),
    ]
