# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0006_auto_20170309_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fijo', models.FloatField(default=0)),
                ('kWh', models.FloatField(default=0)),
                ('AreaCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.AreasControl')),
                ('Mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Meses')),
            ],
        ),
    ]
