# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0007_dac'),
    ]

    operations = [
        migrations.AddField(
            model_name='dac',
            name='Temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Temporada'),
        ),
    ]
