# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0008_dac_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dac',
            name='kWh',
        ),
        migrations.AddField(
            model_name='dac',
            name='Anio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dac',
            name='Costo_kWh',
            field=models.FloatField(default=0),
        ),
    ]
