# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0009_auto_20170309_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basico', models.FloatField(default=0)),
                ('Inter', models.FloatField(default=0)),
                ('Excedente', models.FloatField(default=0)),
                ('CBasico', models.FloatField(default=0)),
                ('CInter', models.FloatField(default=0)),
                ('CExcedente', models.FloatField(default=0)),
                ('Anio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Anio')),
                ('Mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Meses')),
            ],
        ),
        migrations.AddField(
            model_name='tarifa1x',
            name='Anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Anio'),
        ),
    ]
