# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0010_auto_20170314_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa2',
            name='CExcedente',
        ),
    ]
