# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0011_remove_tarifa2_cexcedente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa2',
            name='CBasico',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='tarifa2',
            name='CInter',
            field=models.FloatField(default=50),
        ),
    ]
