# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0013_tarifa2_cargofijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dac',
            name='Anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.Anio'),
        ),
    ]
