# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0020_dac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dac',
            old_name='Costo_kWh',
            new_name='Costo_kWh_fverano',
        ),
        migrations.AddField(
            model_name='dac',
            name='Costo_kWh_verano',
            field=models.FloatField(default=0),
        ),
    ]
