# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0021_auto_20170320_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dac',
            name='Temp',
        ),
    ]
